name: ci

on:
  # Trigger the workflow on push or pull request to main
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: 3.9
        
    steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Checkout repository
      uses: actions/checkout@v2
  
    - name: Install Poetry
      uses: snok/install-poetry@v1
    
    - name: Install package
      run: poetry install
   
    - name: Test with pytest
      run: poetry run pytest tests/ --cov=pycounts_tb --cov-report=xml
      
    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml    # coverage report
        fail_ci_if_error: true
